name: datadog_flags
description: Datadog Feature Flags and Experimentation SDK for Flutter.
version: 0.0.1
publish_to: none
repository: https://github.com/DataDog/dd-sdk-flutter
homepage: https://datadoghq.com

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  http: ^1.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
